### ISSUE TITLE
Problem with ide-helper:models

### ISSUE THREAD

**Issue by WaterSpout** [barryvdh/laravel-ide-helper#534] opened 2017-06-29 01:54 UTC
Hello,
I have used ide-helper:models command and after that, my PhpStorm told me this
![Scrin](http://dl4.joxi.net/drive/2017/06/29/0004/2300/268540/40/dcd2c69423.jpg)

Could you help, please. It's wrong due to SoftDelete methods

**Comment by mfn** [comment] 2020-06-26 12:54
I can't reproduce this, the `@method  … restore()` annotation is not generated for me

@barryvdh Seems this was already fixed some time ago, vote for closing the issue :}

**Closed** 2020-06-26 13:58 UTC

**Comment by mfn** [comment] 2020-06-26 20:12
Btw, this is also backed by the Test `\Barryvdh\LaravelIdeHelper\Tests\Console\ModelsCommand\SoftDeletes\Test` , no restore method in the snapshot => https://github.com/barryvdh/laravel-ide-helper/blob/07d45d2d7a13f3e0345c37062c25103f222539dc/tests/Console/ModelsCommand/SoftDeletes/__snapshots__/Test__test__1.php#L10-L19
