### ISSUE TITLE
Relative class names are not converted to fully-qualified class names (FQCNs)

### ISSUE THREAD

**Issue by davejamesmiller** [barryvdh/laravel-ide-helper#627] opened 2018-02-10 18:22 UTC
In phpDocumentor and PhpStorm, like in PHP, class names that aren't fully-qualified are resolved relative to the namespace and any 'use' statements.

But when the Docblocks are copied into `_ide_helper.php`, it results in invalid relative class names - for example:

```php
namespace DaveJamesMiller\Breadcrumbs;

use DaveJamesMiller\Breadcrumbs\Exceptions\DuplicateBreadcrumbException;

class BreadcrumbsManager
{
    /**
     * @throws DuplicateBreadcrumbException If the given name has already been used.
     */ 
    public function register(string $name, callable $callback)
```

Becomes:

```php
namespace DaveJamesMiller\Breadcrumbs\Facades { 
    class Breadcrumbs {
        /**
         * @throws DuplicateBreadcrumbException If the given name has already been used.
         */ 
        public static function register($name, $callback)
```

PhpStorm sees this as `DaveJamesMiller\Breadcrumbs\Facades\DuplicateBreadcrumbException` instead of `DaveJamesMiller\Breadcrumbs\Exceptions\DuplicateBreadcrumbException`.

In the forked ReflectionDocBlock package I found two issues:

1. The `ReturnTag` class (which is extended by `ParamTag` and `ThrowsTag`) parses the tag to get the type (class) and expand it, but then sets `$this->content` back to the original value, so the FQCN is not used when `getContent()` is called.

https://github.com/barryvdh/ReflectionDocBlock/blob/3dcbd98b5d9384a5357266efba8fd29884458e5c/src/Barryvdh/Reflection/DocBlock/Tag/ReturnTag.php#L50-L60

Setting `$this->content = null;` instead fixes this - `getContent()` then uses the expanded type, resulting in this:

```php
namespace DaveJamesMiller\Breadcrumbs\Facades { 
    class Breadcrumbs {
        /**
         * @throws \DaveJamesMiller\Breadcrumbs\DuplicateBreadcrumbException If the given name has already been used.
         */ 
        public static function register($name, $callback)
```

However, as you can see above, this still doesn't handle 'use' statements, so on its own this has no benefit.

2. I believe the expansion into a FCQN is done by the `Type\Collection::expand()` method, so I tried to compare this to the upstream phpDocumentor class. However, the [parent repo](https://github.com/phpDocumentor/ReflectionDocBlock) is vastly different at this point (looks like it had a major rewrite some time ago), so I can't see a simple fix.

I think the best (but time-consuming) solution might be to switch to the latest upstream version of ReflectionDocBlock. Alternatively it could be added to the current class somehow.

But either way I don't have the energy for that right now, so I thought I'd share my findings here in case anyone else has the same issue and/or wants to take it up.

In the mean time, I'm just going to switch to using FQCNs, as Laravel itself does, for that one class.

**Comment by pSchaub** [comment] 2018-05-22 08:54
Same issue here - this issue still exists.

**Comment by jankal** [comment] 2018-10-09 14:04
@pSchaub @davejamesmiller @MightyPork this seems to be related to #686 
Im experiencing this too.

**Comment by jankal** [comment] 2018-10-09 14:05
@barryvdh ping!

**Comment by mfn** [comment] 2020-06-26 22:29
Doesn't just affect classes, but also native PHP types like iterable => see https://github.com/barryvdh/laravel-ide-helper/issues/673

**Comment by SeinopSys** [comment] 2020-09-25 06:32
Commenting to say the issue is still alive and well until #1005 is merged by the looks of it.

**Comment by jankal** [comment] 2020-12-24 11:53
Copying comment: Commenting to say the issue is still alive and well until #1005 is merged by the looks of it.

**Closed** 2021-03-15 06:45 UTC

**Comment by mfn** [comment] 2021-03-15 19:56
Released via https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.9.1

**Comment by Oleg-Arkhipov** [comment] 2021-03-26 08:10
@mfn are you sure that this works? I generated models stubs with latest v2.9.1 and apparently the situation is the same. For example, `use Carbon\Carbon;` + `@property Carbon $created_at` in original model file (= `Carbon\Carbon` class) results in just '@property Carbon $created_at' (with no `use`) in a stub (= wrong `App\Models\Carbon`)

**Comment by uuf6429** [comment] 2021-04-21 13:48
Same problem here (re `_ide_helper_models.php`). In addition I'm stuck with laravel 6, so this would have to be back-ported to v2.8.x, which I guess is not planned.. 😞
