### ISSUE TITLE
Autocomplete in PHPStorm 2017.1 do not work! :cry:

### ISSUE THREAD

**Issue by fffixed** [barryvdh/laravel-ide-helper#473] opened 2017-03-29 22:04 UTC
I download file .phpstorm.meta.php from [https://gist.github.com/barryvdh/bb6ffc5d11e0a75dba67](https://gist.github.com/barryvdh/bb6ffc5d11e0a75dba67) put it to root folder and restart IDE (PHPStorm 2017.1). Why it do not work?
:cry:

**Comment by jonnywilliamson** [comment] 2017-03-30 13:01
Do you have the laravel plugin enabled (https://github.com/Haehnchen/idea-php-laravel-plugin)?

If so, disable it for the current project and see if that works.

**Comment by fffixed** [comment] 2017-03-30 15:22
I disabled the plugin in my project, and it worked! How so? I thought this plugin was a good thing..

Thank you!

**Comment by jonnywilliamson** [comment] 2017-03-30 15:24
Yeah 

I'm in the process of creating a video to show this problem. 

It should be up here in about 5-6 hours. I'm confused too by it.

**Comment by barryvdh** [comment] 2017-03-30 19:05
@Haehnchen any ideas?

**Comment by Haehnchen** [comment] 2017-03-31 12:03
looks like a regression in PhpTypeProvider2. If reproducible we should should ping someone of the PhpStorm team.

moreover i will also update laraval plugin the next days this will include the new type provider: https://github.com/Haehnchen/idea-php-laravel-plugin/issues/78

**Comment by jonnywilliamson** [comment] 2017-04-01 17:05
So I took a short video

- Installed a completely fresh laravel 5.4 project.
- Added Ide-helper package.
- Have the Laravel Plugin installed but DISABLED for the project.
- Opened PHPStorm and attempt to see if the `fire` method for `app('events')->` would show up as an autocomplete object. Nope.
- Turn on the Laravel plugin. `fire` method still not shown.
- Create the `ide-helper.php` file.
- Still no `fire` method`
- Generate `phpstorm.meta.php` file.
- Still no `fire` method.
- Turn off Laravel Plugin. 
- Finally `fire` method is available.

I don't know how the link between the two projects work, only trying to provide some data to help debug/fix the issue.


Thanks @barryvdh and @Haehnchen .


[![Laravel and IDE Helper bug](https://cloud.githubusercontent.com/assets/2513663/24580704/76df977c-1704-11e7-9bfc-7ba8b956fd22.png)](https://vimeo.com/211104619 "Laravel plugin and IDE-Helper bug")

**Comment by Haehnchen** [comment] 2017-04-02 12:07
@jonnywilliamson Please update plugin to `0.14.1`, this is using PhpStorm 2017.1 API which fixed that issue. if not so please some feedback ;)

**Comment by jonnywilliamson** [comment] 2017-04-02 13:08
@Haehnchen Hey thanks for getting back to me.

With the laravel plugin DISABLED
- Autocomplete for `fire` method not found with new ide-helper/meta file generated.

With the laravel plugin ENABLED
- Autocomplete for `fire` method IS found.


So now I'm a little confused. Should @barryvdh IDE-Helper package (in this case the meta file) not also provide autocomplete for methods like `app('events')->fire`? Or should it only be your plugin that does this!?


[![Laravel and IDE Helper bug](https://cloud.githubusercontent.com/assets/2513663/24587404/c0ca5f26-17ad-11e7-922a-db1006f0b018.png)](https://vimeo.com/211176520 "Laravel plugin and IDE-Helper bug")

**Comment by Haehnchen** [comment] 2017-04-02 13:59
both provide data, source does not matter here. try invalid cache (File Menu) for fresh metadata

I tested all combinations:
![laravel_phpstorm](https://cloud.githubusercontent.com/assets/1011712/24587761/9dee2730-17bc-11e7-9d22-cf89ad0dc6ce.png)

**Comment by fffixed** [comment] 2017-04-02 16:48
After updating the plugin everything works well! Thank you! :dancing_women:

**Comment by jonnywilliamson** [comment] 2017-04-02 21:00
@Haehnchen 

Brilliant. Invalidating the cache worked great. Autocomplete is working well again!

Thanks for the new release. Fantastic stuff!

**Comment by jonnywilliamson** [comment] 2017-04-02 21:05
@fffixed I think you could close this issue.

**Closed** 2017-04-03 00:00 UTC
