### ISSUE TITLE
L5.3 ide-helper:models: No PHPdoc generated

### ISSUE THREAD

**Issue by johlton** [barryvdh/laravel-ide-helper#410] opened 2016-11-24 16:57 UTC
Sorry to ask for help on a similar issue as [#265](https://github.com/barryvdh/laravel-ide-helper/issues/265)

This problem persists on my machine in Laravel 5.3.24 and PHPStorm 2016.2.2 (Build #PS-162.2380.11, built on October 24, 2016) with the latest version of the IDE Helper.

My models sit in app\Models.
Nothing gets written in any file.

`php artisan ide-helper:generate` & `php artisan ide-helper:meta` ran smoothly.

When running ...

`php artisan ide-helper:models`: No error, but nothing written.
`php artisan ide-helper:models User`: No error, but nothing written.
`php artisan ide-helper:models --dir="app\Models"`: No error, but nothing written.
`php artisan ide-helper:models "\App\Models\User"`: Error "Exception: could not find driver. Could not analyze class \App\Models\User."

Really puzzled by this since I managed to get it running approx. a year ago.

Any help would be highly appreciated. Thanks!

**Comment by xseymour** [comment] 2016-11-28 18:06
Also having this issue

**Comment by jeffz2012** [comment] 2016-12-02 22:07
same here

**Comment by rchoffardet** [comment] 2016-12-22 13:32
Are you using the command through phpstorm `Command Line Tools Console` or through your OS Terminal ? 

I had the same issue but while I was trying to debug the package, It just works fine through the terminal :)

**Comment by kaju74** [comment] 2017-01-04 08:00
Same issue here: Inside command line, nothing happens (seems to freeze). In terminal windows, everything works fine. I didn't have this issue some weeks ago. Just updated PHPStorm to EAP 2017.1 - maybe here's the problem?

**Comment by apoca** [comment] 2017-01-12 15:28
I have the same issue...

**Comment by apoca** [comment] 2017-01-12 15:30
[12-Jan-2017 14:42:36 Europe/Lisbon] PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /Applications/MAMP/htdocs/esolidar-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 115

**Comment by Arekusei** [comment] 2017-01-21 11:06
I have the same issue...
But for me worked this command:
`php artisan ide-helper:models "App\User"`

**Comment by apoca** [comment] 2017-01-21 17:42
Unfortunately for me doesn't work with any option, only for few models...

MacBook-Pro-de-Miguel:esolidar-laravel apoca$ php artisan ide-helper:models "App\Models\User"

 Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead? (Yes/No):  (yes/no) [no]:
 > yes

Segmentation fault: 11

**Comment by yljphp** [comment] 2017-02-13 04:23
I have the same issue...

**Comment by yljphp** [comment] 2017-02-13 04:27
'timezone' => 'UTC',

**Comment by fureszk** [comment] 2017-09-20 15:41
thanks @yljphp , it did the trick

**Comment by roballport** [comment] 2017-12-03 21:59
Has always worked fine for me. However in Laravel 5.5.22 models would not generate unless I placed doctrine/dbal in the require, as opposed to "require-dev" of my composer file.

**Comment by apoca** [comment] 2017-12-03 23:39
The problem is when you have a field that is a foreign key with the same name of their related table. For example:

Table name: currency

User has one currency 

The name of the field should be currency_id not currency the same name of their table.

**Comment by liujiasheng** [comment] 2018-03-05 08:26
modify config in _vendor/barryvdh/laravel-ide-helper/config/ide-helper.php_
```php
'model_locations' => array(
    'app\Models',    //your models' location
),
```

**Comment by delmicio** [comment] 2019-01-24 22:11
> 'timezone' => 'UTC',

please explain where to apply this and why does it work.

**Comment by fureszk** [comment] 2019-01-25 09:33
@delmicio config/app.php. I don't know why it helps.

**Comment by uphlewis** [comment] 2020-01-20 18:43
I just came here trying to debug the same issue, turns out we had a Model which had a relation whose name clashed with one of its database columns (laravel docs strictly forbid this!). 

Renaming the relation or migrating the schema to rename the column fixed the issue.

**Comment by mfn** [comment] 2020-01-20 19:12
This is such an old issue and contains so many different comments. The most probably correct one is https://github.com/barryvdh/laravel-ide-helper/issues/410#issuecomment-348830144 .

I vote for closing this.

**Comment by mfn** [comment] 2020-06-25 10:20
@barryvdh see my last comment, I vote for closing this :}

**Closed** 2020-06-25 11:49 UTC
