### ISSUE TITLE
Method not found in PhpStorm

### ISSUE THREAD

**Issue by danilcha** [barryvdh/laravel-ide-helper#348] opened 2016-05-08 10:44 UTC
Trying to make the ide-helper work for all the cases. I enabled helper support in the config, cleared the cache, built the _ide_helper.php and the .phpstorm.meta.php, restarted PhpStorm as described in the documentation. Code completion works for many cases, but not for all. For instance:

**public/index.php**

``` php
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class); // $kernel unresolved
$response = $kernel->handle( // Method 'handle' not found
    $request = Illuminate\Http\Request::capture()
);
$response->send(); // Method 'send' not found
$kernel->terminate($request, $response); // Method 'terminate' not found
```

**database/factories/ModelFactory.php**

``` php
// Method 'define' not found in TheSeer\Autoload\Factory
$factory->define(App\User::class, function (Faker\Generator $faker) {
```

**database/migrations/2014_10_12_000000_create_users_table.php**

``` php
            // Method 'unique' not found in Illuminate\Support\Fluent
            $table->string('email')->unique(); 
```

**app/Http/Middleware/Authenticate.php**

``` php
        // Method 'guard' not found in \Illuminate\Support\Facades\Auth
        if (Auth::guard($guard)->guest()) { 
            if ($request->ajax() || $request->wantsJson()) {
                return response('Unauthorized.', 401);
            } else {
                return redirect()->guest('login'); // Method 'guest' not found in
            }
        }
```

**Comment by shehi** [comment] 2016-05-09 07:51
In such cases just adding /** @var $kernel 
\Illuminate\Contracts\Http\Kernel */ will do the trick. Unfortunately 
this package can't solve all situations of 
auto-completion/object-recognition. Also, everything \Fluent related is 
not supported yet, because that class is generic thing used for many 
things: from collections to Db.

**Comment by shehi** [comment] 2016-05-09 07:52
Additionally, instead of Facades, I recommend using 
app('facade-shortcut-here'), in your case app('auth.driver')

**Comment by danilcha** [comment] 2016-05-11 23:42
Thank you. I'm starting to understand why it does not work in all cases. The facades defined in _ide_helper.php are in global namespace and work only if a php script does not explicitly import the original version, right? So it works with ``Route``, for instance, but does not work with ``Auth``.

The whole Laravel looks like it is written by someone with a background in interpretable languages and Notepad. All those ``Fluent`` (why not define a custom class for column definitions?), magic methods, Facades, ``$app = require_once __DIR__.'/../bootstrap/app.php';`` (wtf?!). The very fact that some facades I have to import and some I don't...

There is a [PhpStorm ticket](https://youtrack.jetbrains.com/issue/WI-851) about implementing external PHPDoc annotations, hope it will improve the situation with Laravel.

**Comment by shehi** [comment] 2016-05-12 07:49
You must have gotten all this upside down :) Because you technically make no sense:

Whatever Facade you want to use in a namespaced script, you need to import it:
```
use \Route,
    \Auth;
```
This is not only about Facades, this is how PHP works: e.g. ```use \Exception;```

Laravel has quite advanced abstraction and design pattern implementation, mostly ported from Ruby.

@barryvdh , I recommend closing this issue, it's rapidly becoming "PHP 101".

**Comment by clytemnestra** [comment] 2016-11-04 10:43
Getting the same problem in ```RedirectIfAuthenticated``` Middleware on a fresh Laravel install. The problem is that by default, Auth is included with ```use Illuminate\Support\Facades\Auth;```, so I have to remove that line and use ```\Auth``` instead, so that PhpStorm knows to look into ```_ide_helper.php```

**Comment by clytemnestra** [comment] 2016-11-04 10:43
Getting the same problem in ```RedirectIfAuthenticated``` Middleware on a fresh Laravel install. The problem is that by default, Auth is included with ```use Illuminate\Support\Facades\Auth;```, so I have to remove that line and use ```\Auth``` instead, so that PhpStorm knows to look into ```_ide_helper.php```

**Comment by matthew-sycle** [comment] 2016-12-09 20:45
Seeing the same issue as @clytemnestra, when we include the full class path for Facades.  We do this for clarity on *which* specific class is being loaded.  

@barryvdh, is there any chance the IDE Helper could add support for full class paths when importing Facades?  e.g. `use Illuminate\Support\Facades\Request;`

**Comment by jonnywilliamson** [comment] 2016-12-10 10:59
Just another voice asking for this too. Thank you Barry.

**Comment by barryvdh** [comment] 2016-12-10 11:20
Nope, only by modifying the vendor files

**Comment by jonnywilliamson** [comment] 2016-12-10 11:25
Ok thanks for the information Barry.

I take it by your response that Taylor and others have already said no to any changing or updating of Laravel docblocks?

I know Graham Campbell is always very "we program for humans not IDE's" orientated - which is fairly frustrating. When you're immersed in the code it's easy to be dismissive of how easy it all is, but for others like me, a little hand holding by the IDE is very welcome and saves me hours of mistakes.

BTW Barry, If I could star this repo more than once I would. It's just SO crazy useful. Thanks for creating it!

**Comment by barryvdh** [comment] 2016-12-10 11:35
Well I think Taylor actually was open to adding some phpdocs and accepted some pull requests lately.. I just meant this package can't do that.

**Comment by matthew-sycle** [comment] 2016-12-15 02:48
I'm not sure if there has been a breaking change made in PHPStorm lately, but I can't get this working for the life of me:
http://itsolutionstuff.com/post/how-to-create-custom-facade-in-laravel-52example.html

I've tried both the pre-generated, and generated my own, `_ide_helper`, generated `.phpstorm.meta.php`, made sure I have the Laravel Plugin installed, but no matter what I do, the "most working" I can get it when I Ctrl-Click on the Facade invocation, it navigates to the class definition in `_ide_helper`, instead of the concrete class being facaded.  

![screen shot 2016-12-14 at 6 45 06 pm](https://cloud.githubusercontent.com/assets/13425073/21210190/d9ba6c86-c22d-11e6-8c81-8cfa12f6626d.png)

Is this package broken for the latest versions of PHPStorm?

Thanks!

**Comment by seanmars** [comment] 2018-03-11 06:21
still get same issue, is there have solution now?

**Comment by AxelGreen** [comment] 2018-06-09 07:36
Here you can find good solution https://github.com/barryvdh/laravel-ide-helper/issues/513#issuecomment-318315583

**Comment by mfn** [comment] 2020-06-25 18:51
This is a problem issue; there are so many different things pointed out, some may already been fixed, some are still present (namespaced returned values in Facades don't work correctly, there are already multiple issues about this)

I encourage everyone still having issues to a) search the existing issues and vote/comment there or b) create new individual issues per encountered problem.

@barryvdh I think https://github.com/barryvdh/laravel-ide-helper/issues/348#issuecomment-218684683 made already the right call and therefore I too suggest to close this issue :}

**Closed** 2020-06-26 05:01 UTC
