### ISSUE TITLE
Cannot redeclare Illuminate\Support\Facades\Route::view()

### ISSUE THREAD

**Issue by andreshg112** [barryvdh/laravel-ide-helper#694] opened 2018-08-31 05:30 UTC
Laravel v5.5.42
Laravel IDE Helper v2.4.3

First Route::view() functon:
![image](https://user-images.githubusercontent.com/15859884/44894338-dc01db00-acb4-11e8-8267-3404289783c6.png)

Second Route::view() function:
![image](https://user-images.githubusercontent.com/15859884/44894361-f63bb900-acb4-11e8-87d3-ffce75df483f.png)

**Comment by mfn** [comment] 2020-06-27 04:09
@barryvdh this is a duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/682 , I vote for closing this issue :}

**Closed** 2020-06-27 08:19 UTC
