### ISSUE TITLE
segmentation fault in "ide-helper:model"

### ISSUE THREAD

**Issue by tsfoer** [barryvdh/laravel-ide-helper#339] opened 2016-04-01 07:52 UTC
Since several months i'm faced with a nasty segmentation fault whenever i call "php artisan ide-helper:model":

```
$ php artisan ide-helper:model
 Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead? (Yes/No):  (yes/no) [no]:
 > no

Segmentation fault
```

I've tried the same on 3 different servers with different php-versions (5.5, 5.6 and 7.0) and it's always segfaulting.

According to "strace -f php artisan ide-helper:model" it crashes on memory allocation after reading one of my model files:

> lstat("/home/xx/xx/laravel/xx/app/UserData.php", {st_mode=S_IFREG|0644, st_size=2282, ...}) = 0
> open("/home/xx/xx/laravel/xx/app/UserData.php", O_RDONLY) = 6
> fstat(6, {st_mode=S_IFREG|0644, st_size=2282, ...}) = 0
> lseek(6, 0, SEEK_CUR)                   = 0
> close(7)                                = 0
> lseek(6, 0, SEEK_SET)                   = 0
> read(6, "<?php\n\nnamespace App;\n\nuse Illum"..., 8192) = 2282
> brk(0x2ee7000)                          = 0x2ee7000
> brk(0x2f27000)                          = 0x2f27000
> brk(0x2f67000)                          = 0x2f67000
> brk(0x2fa7000)                          = 0x2fa7000
> brk(0x2fe7000)                          = 0x2fe7000
> brk(0x3027000)                          = 0x3027000
> brk(0x3067000)                          = 0x3067000
> mmap(NULL, 528384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f985580e000
> brk(0x27c5000)                          = 0x27c5000
> brk(0x2805000)                          = 0x2805000
> brk(0x2845000)                          = 0x2845000
> brk(0x2885000)                          = 0x2885000
> brk(0x28c5000)                          = 0x28c5000
> brk(0x2905000)                          = 0x2905000
> brk(0x2945000)                          = 0x2945000
> brk(0x2985000)                          = 0x2985000
> brk(0x29c5000)                          = 0x29c5000
> brk(0x2a05000)                          = 0x2a05000
> brk(0x2a45000)                          = 0x2a45000
> mremap(0x7f985580e000, 528384, 790528, MREMAP_MAYMOVE) = 0x7f985574d000
> brk(0x2a85000)                          = 0x2a85000
> brk(0x2ac5000)                          = 0x2ac5000
> brk(0x2b05000)                          = 0x2b05000
> brk(0x2b45000)                          = 0x2b45000
> brk(0x2b85000)                          = 0x2b85000
> brk(0x2bc5000)                          = 0x2bc5000
> brk(0x2c05000)                          = 0x2c05000
> brk(0x2c45000)                          = 0x2c45000
> brk(0x2c85000)                          = 0x2c85000
> brk(0x2cc5000)                          = 0x2cc5000
> brk(0x2d05000)                          = 0x2d05000
> brk(0x2d45000)                          = 0x2d45000
> brk(0x2d85000)                          = 0x2d85000
> brk(0x2dc5000)                          = 0x2dc5000
> brk(0x2e05000)                          = 0x2e05000
> brk(0x2e45000)                          = 0x2e45000
> brk(0x2e85000)                          = 0x2e85000
> brk(0x2ec5000)                          = 0x2ec5000
> brk(0x2f05000)                          = 0x2f05000
> brk(0x2f45000)                          = 0x2f45000
> brk(0x2f85000)                          = 0x2f85000
> brk(0x2fc5000)                          = 0x2fc5000
> brk(0x3005000)                          = 0x3005000
> brk(0x3045000)                          = 0x3045000
> brk(0x3085000)                          = 0x3085000
> mremap(0x7f985574d000, 790528, 1314816, MREMAP_MAYMOVE) = 0x7f985574d000
> brk(0x30c5000)                          = 0x30c5000
> brk(0x3105000)                          = 0x3105000
> brk(0x3145000)                          = 0x3145000
> brk(0x3185000)                          = 0x3185000
> brk(0x31c5000)                          = 0x31c5000
> brk(0x3205000)                          = 0x3205000
> brk(0x3245000)                          = 0x3245000
> brk(0x3285000)                          = 0x3285000
> brk(0x32c5000)                          = 0x32c5000
> brk(0x3305000)                          = 0x3305000
> brk(0x3345000)                          = 0x3345000
> brk(0x3385000)                          = 0x3385000
> brk(0x33c5000)                          = 0x33c5000
> brk(0x3405000)                          = 0x3405000
> brk(0x3445000)                          = 0x3445000
> --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7fff0c871fd8} ---
> +++ killed by SIGSEGV +++
> Segmentation fault

The model consists of normal attributes like "$fillable[]" and "$dates[]" and some "hasOne()" relation functions, nothing special in my opinion. I also can't remember at what point of my application development the crashes appeared.

Is there a way to debug this as I'd like to use the ide-helper again :/

Laravel 5.1
ide-helper 2.1.4

Thanks a lot
Thomas

**Comment by timhaak** [comment] 2016-04-11 12:10
I've also just hit this bug. Though for me it's only started recently.

**Comment by timhaak** [comment] 2016-04-11 14:43
Ok I've tracked mine down to something that seems to have changed with php7 that now errored on a circular dependency.  Which it should :).

**Comment by tsfoer** [comment] 2016-04-17 12:49
@timhaak how did you track this down?

**Comment by timhaak** [comment] 2016-04-17 18:25
I traced through the code till I found where it was segfaulting.

Saw that it was while processing some of my classes but was processing some fine then looked to see what the difference between them was. 

Part of the problem as said was the php 5.6 was processing them fine but shouldn't have.

**Comment by ivan1911** [comment] 2016-09-09 09:46
So anyone resolve this problem? (save same btw)

**Comment by spmsupun** [comment] 2017-12-17 12:56
anyone got fixed the issue ?

**Comment by timhaak** [comment] 2017-12-18 07:26
In my case the issues was not the IDE helper but a newer version of PHP that was not behaving correctly and throwing an issue that it should have previously.

Are all your models giving the error or only some?

If all then a diffrent problem, if only some compared what is diffrent.

**Comment by uphlewis** [comment] 2020-01-20 18:43
I just came here trying to debug the same issue, turns out we had a Model which had a relation whose name clashed with one of its database columns (laravel docs strictly forbid this!).

Renaming the relation or migrating the schema to rename the column fixed the issue.

**Comment by mfn** [comment] 2020-01-20 19:12
Segmention faults, unless cause with some recursive loop, are hardly a bug of the library.

I vote for closing this issue.

(also: bug reported 4 years ago… so much changed since then)

**Comment by uphlewis** [comment] 2020-01-21 10:21
> Segmention faults, unless cause with some recursive loop, are hardly a bug of the library.

Actually in normal circumstances having an attribute + relationship name clash in an Eloquent model doesnt cause a recursive loop by itself- the way the library inspects models means this leads to a recursive loop.

I understand the want to close old issues but it would be cool if this could be addressed - I dont imagine it would be hard to detect and print out a warning or something instead of letting it run into a crash.

Happy to take a look if you accept PRs ?

**Comment by mfn** [comment] 2020-01-21 12:12
If you ask me, totally up for an PR with tests (there were recently added some!) 😄

**Comment by mfn** [comment] 2020-06-25 15:52
I think if someone could provide a step-by-step how to reproduce this, it's easier to look into this. Note that we're talking about something which is by itself already a bug in the application (this recursive property/database case), so I'm not sure what ide-helper really could do in case of buggy code.

@barryvdh due to lack of further feedback I vote for closing :}

**Closed** 2020-06-25 16:25 UTC
