### ISSUE TITLE
IdeHelper assumes all referenced classes are in the same namespace as the façade'd class

### ISSUE THREAD

**Issue by MightyPork** [barryvdh/laravel-ide-helper#686] opened 2018-07-30 14:05 UTC
I can't explain this bug any other way.. It is Laravel 5.5, ide helper 2.4.3. I tried updating and it didn't help.

Situation:

- I have a `Permission` façade pointing to `\App\PermissionManager`, registered and working correctly.
- Models live in `\App\Models`.
- There are methods on my User model like this:

```php
use Permission;
use Illuminate\Support\Collection;
// Component is a Model in the same folder
...
	/**
	 * @param string|string[] $permission
	 * @return Collection|Component[]
	 */
	public function getComponentsWhereCan($permission)
	{
		return Permission::getComponentsWhereCan($this, $permission);
	}
```

And this is the called method in the Façade'd class:

```php

use App\Models\Component;
use App\Models\User;
use Illuminate\Support\Collection;
/**
	 * Get components where user can do any of the given actions/permissions
	 *
	 * @param User $user
	 * @param string|string[] $permission
	 * @return Collection|Component[]
	 */
	public function getComponentsWhereCan(User $user, $permission)
	{ ...
```

Here is what the Helper generated for the façade in `_ide_helper.php`, ignoring the `use` statements and the folder and namespace the model was in.

```php
        /**
         * Get components where user can do any of the given actions/permissions
         *
         * @param \App\User $user <-- wrong
         * @param string|string[] $permission
         * @return \App\Collection|\App\Component[]  <-- both wrong
         * @static 
         */ 
        public static function getComponentsWhereCan($user, $permission)
        {
            return \App\PermissionManager::getComponentsWhereCan($user, $permission);
        }        
```

(this of course results in a big yellow highlight with red squiggly lines in phpstorm, because all the namespaces except for `PermissionManager`, my façade'd class, are wrong.)

This happened to every method of the `Permission` façade that references any of my models

Here's my autoload

```json
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": [
				"app/"
			]
		},
		"files": [
			"app/helpers.php"
		]
	},
	"autoload-dev": {
		"psr-4": {
			"Tests\\": "tests/"
		},
		"classmap": [
			"tests/TestCase.php",
			"tests/BrowserKitTestCase.php"
		]
	},
```

Nothing unusual I would say. I'm not sure I can get a minimal example, it's a large proprietary project.
Those confused namespaces can be found in most of my façades that use type hints, but vendor ones seem OK.

(note: I use a different base name instead of `App`, it was redacted in the examples above)

(my config file is basically stock, with `'model_locations' => array('app/Models',),`, but I understand that's not used by the :generate command anyway)

**Comment by MightyPork** [comment] 2018-07-30 14:30
Fun observation, now i went through the entire façaded class and changed all typehints to FQN, and it worked OK. So that's a work-around, not great but good enough for my immediate needs

**Comment by jankal** [comment] 2018-10-09 14:02
@MightyPork I can relate. Experiencing this too.

**Comment by jankal** [comment] 2018-10-09 14:05
@barryvdh

**Comment by mborek-elastique** [comment] 2018-11-22 06:46
bumping that up, for me the same :) @barryvdh

**Comment by mfn** [comment] 2020-06-27 03:59
@barryvdh this is a duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/627 , I vote for closing this issue :}

**Closed** 2020-06-27 08:20 UTC
