### ISSUE TITLE
request()->validate(); Not found

### ISSUE THREAD

**Issue by awais-vteams** [barryvdh/laravel-ide-helper#744] opened 2018-12-20 14:42 UTC
request()->validate(); is not handling in latest Laravel 5.7.15. It's showing undefined.

**Comment by apintocr** [comment] 2018-12-23 20:01
I can also confirm this.
Using latest Laravel on a fresh setup.

**Comment by SalemCode8** [comment] 2019-01-18 12:17
use $this->validate($request, $rule);

in the controller instead

**Comment by apintocr** [comment] 2019-01-21 10:51
Thank you.
I understand the workarounds, I was only reporting an issue :)

ᐧ

**Comment by hackel** [comment] 2019-11-05 19:26
Dupe of #608.

**Comment by mfn** [comment] 2020-06-27 04:42
This works since Laravel 6 because it was added in the framework phpdoc => https://github.com/laravel/framework/pull/30975

@barryvdh issue can be closed :}

**Closed** 2020-06-27 08:08 UTC
