### ISSUE TITLE
Installation failed, reverting ./composer.json to its original content.

### ISSUE THREAD

**Issue by 0x25101994** [barryvdh/laravel-ide-helper#356] opened 2016-06-13 02:43 UTC
C:\Users\James\PhpstormProjects\thanhlong>composer require barryvdh/laravel-ide-helper
Using version ^2.1 for barryvdh/laravel-ide-helper
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpdocumentor/reflection-docblock (locked at 3.1.0) -> satisfiable by phpdocumentor/reflection-docblock[3.1.0].
    - barryvdh/laravel-ide-helper v2.1.0 requires phpdocumentor/reflection-docblock 2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
    - barryvdh/laravel-ide-helper v2.1.1 requires phpdocumentor/reflection-docblock 2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
    - barryvdh/laravel-ide-helper v2.1.2 requires phpdocumentor/reflection-docblock 2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
    - barryvdh/laravel-ide-helper v2.1.3 requires phpdocumentor/reflection-docblock ^2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
    - barryvdh/laravel-ide-helper v2.1.4 requires phpdocumentor/reflection-docblock ^2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
    - Conclusion: don't install phpdocumentor/reflection-docblock 2.0.4
    - Installation request for barryvdh/laravel-ide-helper ^2.1 -> satisfiable by barryvdh/laravel-ide-helper[v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4].

Installation failed, reverting ./composer.json to its original content.

----
I have tried install it many times but its not working. Please help me.

**Comment by chinayrzpin** [comment] 2016-06-13 04:20
I also happen the same mistake

**Comment by p3ym4n** [comment] 2016-06-13 05:39
same happen for me.

**Comment by barryvdh** [comment] 2016-06-13 06:53
Duplicate of #352

**Closed by barryvdh** 2016-06-13 06:53 UTC
