### ISSUE TITLE
Autocomplete in model not working in PhpStorm

### ISSUE THREAD

**Issue by Alymosul** [barryvdh/laravel-ide-helper#542] opened 2017-07-23 14:44 UTC
PhpStorm is unable to autocomplete only in models, it also fails to autocomplete built-in php functions, but when a model extends Eloquent instead of Model the autocomplete works correct and also when i generate phpdocs for the models using the comman php artisan ide-helper:models it works.

without ide-helper:models and extends Model
![image](https://user-images.githubusercontent.com/8314647/28500296-03708c40-6fc6-11e7-8781-2f0db6bc8457.png)

with ide-helper:models
![image](https://user-images.githubusercontent.com/8314647/28500300-157e0f8e-6fc6-11e7-8957-c11a84e6827e.png)

I am using Laravel 5.4.30

**Comment by kmare** [comment] 2017-07-24 02:56
see #541 , hopefully it'll get fixed soon. It's kinda annoying.

**Comment by Artistan** [comment] 2017-07-24 13:26
https://github.com/barryvdh/laravel-ide-helper/issues/541#issuecomment-317411918
this includes issue with PhpStorm not handling dynamic method calls via __callStatic on a non-static method

This is a duplicate of the linked issue.

**Comment by Artistan** [comment] 2017-08-01 01:36
this update would make automate the adding of the mixin via the ide-helper commands...
https://github.com/barryvdh/laravel-ide-helper/pull/544

**Comment by mfn** [comment] 2020-06-26 20:35
@barryvdh this is another issue fixed with the `@mixin` and can be closed :}

**Closed** 2020-06-26 20:38 UTC
