### ISSUE TITLE
Support for composite primary keys

### ISSUE THREAD

**Issue by sptdigital** [barryvdh/laravel-ide-helper#706] opened 2018-09-12 13:30 UTC
When declaring an Eloquent model with a composite primary key the following error is always returned upon running of the Models helper ...

```
Exception: Illegal offset type in isset or empty
```

Do you plan on adding support for composite primary keys?

**Comment by isclopezm** [comment] 2018-11-12 23:30
I have the same problem. I'm using the package _awobaz/compoships_, which allows using composite primary keys and when I run the _ide-helper:models_ command I get that error.

**Comment by Mochaka** [comment] 2019-01-25 00:37
I'm also getting this error on the same package, is there any fix?

**Comment by Mochaka** [comment] 2019-01-25 00:45
i patched it by modifying a line in `vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php:552`

change

`return isset($this->nullableColumns[$fkProp->getValue($relation)]);`

to 

` return isset($this->nullableColumns[is_array($fkProp->getValue($relation)) ? $fkProp->getValue($relation)[0] : $fkProp->getValue($relation)]);`

it doesn't really fix it, it just stops the error coming up

**Comment by burut13** [comment] 2019-12-29 15:19
Anything new on this issue?

I'd like to mention that it only occurs with `belongsTo` relationship, while working just fine with `hasMany`. Haven't tested other relationship types.

**Comment by deare** [comment] 2020-01-28 14:17
The error occurs when you use a model that has a composite primary key.
In the case of composite primary keys, also write in your model:
_public $incrementing = false;_

**Comment by mpyw** [comment] 2020-04-24 22:21
@sptdigital @isclopezm @aaronflorey @burut13 @deare (CC @barryvdh)

Quick fix for this issue (requires `barryvdh/laravel-ide-helper^2.7` `php>=7.4`):

```php
<?php

namespace App\Console\Commands\IdeHelper;

use Barryvdh\LaravelIdeHelper\Console\ModelsCommand as BaseModelsCommand;
use Illuminate\Support\Arr;
use Illuminate\Database\Eloquent\Relations\Relation;

class ModelsCommand extends BaseModelsCommand
{
    /**
     * @param  string   $relation
     * @param  Relation $relationObj
     * @return bool
     */
    protected function isRelationNullable(string $relation, Relation $relationObj): bool
    {
        $reflectionObj = new \ReflectionObject($relationObj);

        if (in_array($relation, ['hasOne', 'hasOneThrough', 'morphOne'], true) || !$reflectionObj->hasProperty('foreignKey')) {
            return parent::isRelationNullable($relation, $relationObj);
        }

        $fkProp = $reflectionObj->getProperty('foreignKey');
        $fkProp->setAccessible(true);

        return (bool)Arr::first(
            (array)$fkProp->getValue($relationObj),
            fn (string $value) => isset($this->nullableColumns[$value])
        );
    }
}
```

**Comment by mfn** [comment] 2020-06-27 04:16
But does Laravel officially support this?

The docs don't mention it ( checked https://laravel.com/docs/7.x/eloquent ), so it might work rather by accident? 🤷‍♀️

**Comment by burut13** [comment] 2020-06-27 04:16
Spostovani,
do ponedeljka, 29.6.2020 sem odsoten. Na posto bom odgovoril glede na pomembnost zadeve takoj, ko bo mogoce.
Za nujne zadeve pisite na urgent@u-cart.si ali poklicite +386 40 847 061, Damijan.
Hvala za razumevanje in lep pozdrav,
Borut


Hi there,
I'll be out of office until June 29th 2020. I will reply to your e-mail when I get a chance.
For urgent matters please contact us at urgent@u-cart.si or call +386 40 847 061, Damijan.
Thank you for your understanding and best regards,
Borut

**Comment by mfn** [comment] 2020-06-27 09:01
@barryvdh there's another issue with a possible (code) workaround, I suggest to close this as duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/838

**Closed** 2020-06-27 10:37 UTC

**Comment by maned3v** [comment] 2022-01-20 14:41
I'm facing the same problem in version 2.10 and solved by checking each compoships array key element:

...\web\vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php
```
protected function isRelationNullable(string $relation, Relation $relationObj): bool
    {
        $reflectionObj = new ReflectionObject($relationObj);

        if (in_array($relation, ['hasOne', 'hasOneThrough', 'morphOne'], true)) {
            $defaultProp = $reflectionObj->getProperty('withDefault');
            $defaultProp->setAccessible(true);

            return !$defaultProp->getValue($relationObj);
        }

        if (!$reflectionObj->hasProperty('foreignKey')) {
            return false;
        }

        $fkProp = $reflectionObj->getProperty('foreignKey');
        $fkProp->setAccessible(true);

        //Compoships
        if (is_array($fkProp->getValue($relationObj))) {
            foreach ($fkProp->getValue($relationObj) as $key) if (!isset($this->nullableColumns[$key])) return false;
            return true;
        }

        return isset($this->nullableColumns[$fkProp->getValue($relationObj)]);
    }
```
