### ISSUE TITLE
[BUG] Error when running with  "doctrine/dbal": "3.0"

### ISSUE THREAD

**Issue by ekpono** [barryvdh/laravel-ide-helper#1133] opened 2020-12-22 17:37 UTC
When running laravel-ide-helper on new Laravel 8 with  doctrine/dbal 3.0 it throws an error

**Comment by ekpono** [comment] 2020-12-22 17:37
<img width="1440" alt="Screen Shot 2020-12-22 at 6 36 09 PM" src="https://user-images.githubusercontent.com/35940495/102917018-c23bc180-4484-11eb-9730-4bfedbd2ee83.png">

**Comment by mfn** [comment] 2020-12-23 06:57
Duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/1079

**Closed by mfn** 2020-12-23 06:57 UTC
Labels: bug
