### ISSUE TITLE
Macro support doesn't work

### ISSUE THREAD

**Issue by aledelgo** [barryvdh/laravel-ide-helper#531] opened 2017-06-27 09:12 UTC
[Note i've previously posted this message as [comment](https://github.com/barryvdh/laravel-ide-helper/pull/500#issuecomment-310622506)  on the Macro feature PR but it seems i've got no visibility, hope this don't violate any rule ]

Unfortunately on my environment it doesn't works fine well... i'm on PhpStorm with laravel 5.3

i have this code in a custom registered provider (my code is working fine)

```
class ResponseMacroServiceProvider extends ServiceProvider {

    /**
     * Perform post-registration booting of services.
     *
     * @return void
     */
    public function boot()
    {



        /**
         * Create a response()->apiResponse(...) function
         */
        Response::macro('apiResponse', function($apiResultObj, $serializazionGroups=null, $includeDefaultGroups=true, $jsonPCallback=null)
        {

            /* custom code here...*/

            return $resp;


        });
    }

}
```

I see ide-helper correctly generate this in __ide_helper.php_ file

```
/**
         * Create a response()->apiResponse(.
         * 
         * ..) function
         *
         * @static 
         */ 
        public static function apiResponse($apiResultObj, $serializazionGroups = null, $includeDefaultGroups = true, $jsonPCallback = null)
        {
            return \Illuminate\Routing\ResponseFactory::apiResponse($apiResultObj, $serializazionGroups, $includeDefaultGroups, $jsonPCallback);
        }
```

but the IDE don't recognize it in the autocomplete list.
when i write:
` return response()->apiResp`
the method is not listed in the autocomplete list, and if i write it completely like 
`return response()->apiResponse($result, [], false);`
the method is underlined and marked with a tooltip sayng the method is not found 
![image](https://user-images.githubusercontent.com/1503438/27476429-0625c466-5809-11e7-94b0-6582b0396463.png)

Do you have any idea?

**Comment by mostafamiri65** [comment] 2017-11-17 17:37
I use `appstract/laravel-response-macros` for my laravel passport.
`ide-helper` can not handle new methods from this package.

    public function run($factory)
    {
        $factory->macro('error', function ($message, $status) use ($factory) {
            return $factory->make([
                'status' => 'error',
                'error' => $message,
            ], $status);
        });
    }

**Comment by vpratfr** [comment] 2018-03-09 09:21
Got some macros defined in my TestCase base class and they do not get picked up either. What is the way to get our macros picked up by ide-helper? Any configuration parameter could help?

**Comment by crhg** [comment] 2018-09-07 01:26
Currently, macro support is implemented as part of facade alias processing, so the target class must be registered as a facade with an alias. (Eg included in `aliases` in `config/app.php`)

Laravel has many classes that have the ability to define macro but not facade. (ex `\Illuminate\Support\Arr`, `\Illuminate\Support\Collection`, `\Illuminate\Validation\Rule`,...)  For this reason they are not the target of macro support.

One workaround is to prepare appropriate aliases for those classes and add them to `aliases` in `config/app.php`. For example:

```php
    'aliases' => [
        ......

        'Collection' => \Illuminate\Support\Collection::class,
    ],
```

Note: 
I think this will work for most classes, but it doesn't work for  `\Illuminate\Database\Eloquent\Builder`. This is because the current macro support judges whether or not the class has the macro function by judging whether or not the class uses the `\Illuminate\Support\Traits\Macroable` trait, `\Illuminate\Database\Eloquent\Builder` does not use the `Macroable` trait and has its own implementation.

**Comment by LastDragon-ru** [comment] 2019-06-03 07:25
> but it doesn't work for \Illuminate\Database\Eloquent\Builder

`vendor/barryvdh/laravel-ide-helper/src/Alias.php`

Find:
`if ($traits->contains('Illuminate\Support\Traits\Macroable')) {`

Replace to
`if ($traits->contains('Illuminate\Support\Traits\Macroable') || $reflection->getName() === Builder::class) {`

And it will work :) (laravel 5.8)

**Comment by spencero91** [comment] 2019-06-20 23:39
It doesn't seem to find macros in custom service providers.... Or at least it isn't for the Cache facade.

**Comment by roni-estein** [comment] 2019-09-17 23:37
@spencero91 were you able to figure this out? I've run into this situation where I've been curating macros definitions into an AutoCompleteHelper.php. That all works beautifully, however, if some macros are coming from different packages that are being used internally, if the next project has more macros or uses doesn't use all the macro's of the first file, you wind up having to manually curate that helper file.

Extracting the helper file to the package seems like the obvious win, and it will work if you open the file up with phpstorm, and let it index it manually. However, if you make a change in the file in another IDE for example, to model something like a composer update where it changes behind the scenes, it won't update in PHPstorms index. If you do the same thing to the regular AutoCompleteHelper behind the scenes, it seems like it will update.

This is probably a horrible solution, but the first thing that crosses my mind, is to add a command to composer dump-autoload that reads all packages for an AutoCompleteHelper.php, and then basically merge them into some safe space like config/autocomplete.php

If anyone has solved this already and better please advise.

I've got the rest working, so it seemed like a good idea to move the macro definitions into packages th

**Comment by roni-estein** [comment] 2019-09-19 03:42
I wrote a small package that uses some of the advice here to solve my own use case, which deals with TestCase Macros as well as macros in packages. It's not the coolest solution but it does work. you can find it at https://github.com/roni-estein/package-macro-autocomplete

**Comment by mfn** [comment] 2020-06-27 20:12
@barryvdh this is a duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/40 and thus can be closed

**Closed** 2020-06-27 20:24 UTC
