### ISSUE TITLE
Call to a member function getMethods() on null

### ISSUE THREAD

**Issue by celorodovalho** [barryvdh/laravel-ide-helper#1084] opened 2020-10-24 21:58 UTC
### Versions:
- ide-helper Version: dev-master (2.8.1)
- Laravel Version: 8.9.0
- PHP Version: 7.4.8

### Description:

I recently try to run the command below and I got this error:

```php
$ artisan ide-helper:generate                                             

   Error 

  Call to a member function getMethods() on null

  at vendor/barryvdh/laravel-ide-helper/src/Macro.php:64
     60▕     {
     61▕         $enclosingClass = $this->method->getClosureScopeClass();
     62▕ 
     63▕         /** @var \ReflectionMethod $enclosingMethod */
  ➜  64▕         $enclosingMethod = Collection::make($enclosingClass->getMethods())
     65▕             ->first(function (\ReflectionMethod $method) {
     66▕                 return $method->getStartLine() <= $this->method->getStartLine()
     67▕                     && $method->getEndLine() >= $this->method->getEndLine();
     68▕             });

      +32 vendor frames 
  33  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

```

### Steps To Reproduce:

- artisan ide-helper:generate

**Comment by mfn** [comment] 2020-10-29 15:59
Can you debug which method this is about?

Also maybe the code is simply buggy as `getClosureScopeClass` can return `null`, but nevertheless would be good to understand what specifically triggers this.

**Comment by standaniels** [comment] 2020-12-10 10:30
This seems to be caused by invokable classes. This how to reproduce this issue:

**Versions**:

- laravel/framework 8.18.1
- barryvdh/laravel-ide-helper 2.8.2
- PHP 7.4.10


## Step 1.

Create class `App\Foo`:

```php
<?php

namespace App;

class Foo
{
    public function __invoke($var)
    {
        return $var;
    }
}
```

## Step 2.

Register the macro by passing a new instance of `App\Foo`:

```php
<?php

namespace App\Providers;

use App\Foo;
// ...

class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        UrlGenerator::macro('foo', new Foo());
    }

    // ...
}
```

## Step 3.

Run `php artisan ide-helper:generate`.

## Result

```
   Error

  Call to a member function getMethods() on null

  at vendor/barryvdh/laravel-ide-helper/src/Macro.php:64
     60▕     {
     61▕         $enclosingClass = $this->method->getClosureScopeClass();
     62▕
     63▕         /** @var \ReflectionMethod $enclosingMethod */
  ➜  64▕         $enclosingMethod = Collection::make($enclosingClass->getMethods())
     65▕             ->first(function (\ReflectionMethod $method) {
     66▕                 return $method->getStartLine() <= $this->method->getStartLine()
     67▕                     && $method->getEndLine() >= $this->method->getEndLine();
     68▕             });

      +30 vendor frames
  31  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Logging the value of `$this->method` at `src/Macro.php:62` results in the following log entry:

```
[2020-12-10 10:26:38] local.DEBUG: Closure [ <user> public method Illuminate\Foundation\Providers\{closure} ] {
  @@ /Users/standaniels/Desktop/temp/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php 83 - 85
}
  
[2020-12-10 10:26:38] local.DEBUG: Method [ <user> public method __invoke ] {
  @@ /Users/standaniels/Desktop/temp/app/Foo.php 7 - 10

  - Parameters [1] {
    Parameter #0 [ <required> $string ]
  }
}
```

**Comment by mfn** [comment] 2020-12-10 20:18
I don't use these kind of things 🤷‍♀️

Can you propose a PR / test to fix this?

**Comment by mfn** [comment] 2021-01-09 15:58
Fixed with https://github.com/barryvdh/laravel-ide-helper/pull/1124

**Closed by mfn** 2021-01-09 15:58 UTC
Labels: bug

**Comment by mfn** [comment] 2021-03-15 19:56
Released via https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.9.1

**Comment by peterchaula** [comment] 2021-05-31 10:39
@mfn the PR seems to have broken some of my classes. `ReflectionMethod::getClosureScopeClass()` returns null for non closures. See example below:

![image](https://user-images.githubusercontent.com/13304490/120181201-0342b980-c20d-11eb-9a5b-46c8cdae8bc5.png)


 I'm proposing this change as a fix. I'll submit a PR if you're happy with the change
 
 
![image](https://user-images.githubusercontent.com/13304490/120181362-3ab16600-c20d-11eb-818d-ae1058a42291.png)

**Comment by mfn** [comment] 2021-05-31 12:19
But this change then will not support `__invoke`able classes?

Basically: yes, please make a PR but from a quick look just replacing it with `isClosure` might not be correct

**Comment by peterchaula** [comment] 2021-05-31 13:23
@mfn thanks. I'll have another look at my proposed change and make changes if necessary and create the PR. Thanks.

**Comment by terry-lonesski** [comment] 2021-06-23 10:09
I still have 
**Call to a member function getMethods() on null** 
at **vendor/barryvdh/laravel-ide-helper/src/Macro.php**


```
/** @var \ReflectionMethod $enclosingMethod */
        $enclosingMethod = Collection::make($enclosingClass->getMethods())
            ->first(function (\ReflectionMethod $method) {
                return $method->getStartLine() <= $this->method->getStartLine()
                    && $method->getEndLine() >= $this->method->getEndLine();
            });
```

in some cases $enclosingClass is null
  
I have 2.10.0 version installed

**Comment by JanMisker** [comment] 2021-08-03 20:44
I also still have this issue. I enabled debugging and I can see that the problem stems from some other package I installed that adds a macro on the Request.

[Request::macro(...)](https://github.com/DarkGhostHunter/Captchavel/blob/8f8953589acdf14e8885fb90179a6ca397223562/src/CaptchavelServiceProvider.php#L51)

This causes a problem in `addLocationToPhpDoc()`

**Comment by JanMisker** [comment] 2021-08-03 20:52
I propose a quick, probably naive, fix here: https://github.com/barryvdh/laravel-ide-helper/pull/1239
