### ISSUE TITLE
Run "php artisan ide-helper:models --write" command on "php7.3" will report an error

### ISSUE THREAD

**Issue by codeyifei** [barryvdh/laravel-ide-helper#776] opened 2019-03-04 03:43 UTC
When I run the ide-helper:models command with php7.3, I get the following error:
Stripos(): Non-string needles will be interpreted as strings in the future. Use an explicitchr() call to preserve the current behavior
Check php's manual found that stripos() has been deprecated in version 7.3
![image](https://user-images.githubusercontent.com/30040950/53709329-acee4100-3e72-11e9-90b1-d773ddd970e4.png)

**Comment by hangzhouyifei** [comment] 2019-03-04 03:44
![image](https://user-images.githubusercontent.com/30040950/53709352-ce4f2d00-3e72-11e9-94d1-345b1d6d4f89.png)

**Comment by octoxan** [comment] 2019-03-04 18:11
Same. Mine just seems to fail on any model that has a relationship, oddly.

**Comment by LauLogisch** [comment] 2019-08-01 10:04
Same. @codeyifei Thank you for the solution.

**Comment by mfn** [comment] 2019-08-01 20:14
> found that stripos() has been deprecated in version 7.3

This is not correct, from https://www.php.net/manual/en/function.stripos.php

> If **needle** is not a string, it is converted to an integer and applied as the ordinal value of a character. This behavior is deprecated as of PHP 7.3.0, and relying on it is highly discouraged. Depending on the intended behavior, the **needle** should either be explicitly cast to string, or an explicit call to [chr()](https://www.php.net/manual/en/function.chr.php) should be performed. 

Only a specific aspect is deprecated.

Btw, I'm on 7.3.7 and using 2.6.2 of this package and can't reproduce this (and I've a lots of models with lots of relations).

Apparently this has been fixed via https://github.com/barryvdh/laravel-ide-helper/pull/774 so the proper solution is to upgrade.

**Comment by mfn** [comment] 2020-06-27 05:02
@barryvdh see my last comment, this is fixed and can be closed :}

**Closed** 2020-06-27 08:06 UTC
