### ISSUE TITLE
Wrong Exception detected

### ISSUE THREAD

**Issue by ADRDev** [barryvdh/laravel-ide-helper#580] opened 2017-10-10 13:47 UTC
When I use \DB::beginTransaction() it detects that it throws \Illuminate\Support\Facades\Exception instead of the root namespace \Exception.

beginTransaction() in _ide_helper.php is getting decorated with @throws Exception which is relative to the \Illuminate\Support\Facades namespace.

I would imagine the same thing is happening in other instances as well.

**Comment by mfn** [comment] 2020-06-26 21:17
It works for ` \DB::beginTransaction()` nowadays.

Basically, ide-helper isn't capable of resolving this on its own, rather relies on phpdocs using FQCN because they're just copied over. Laravel does have a habit of always using FQCN but in some cases it doesn't.

Also this easily breaks with Facades from 3rd party package which just don't use FQCN for such sort of things.

I can see the issue; ide-helper would need to be smarter and convert imports to FQCN.

I guess this is the same issue as with many other bugs reported in that Facades copy over the data but ignore `use` imports.

**Comment by mfn** [comment] 2020-06-27 20:20
Actually I was wrong!

@barryvdh this a duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/627 which contains better details; I suggest to close this one in favour of the other :}

**Closed** 2020-06-27 20:23 UTC
Labels: enhancement
