### ISSUE TITLE
PhpStorm detecting multiple declarations for models and facades

### ISSUE THREAD

**Issue by Glendog** [barryvdh/laravel-ide-helper#900] opened 2020-03-17 21:36 UTC
Hello,

Since using ide-helper, I am getting class undefined for my facades and models. When I control click them PhpStorm offers multiple declarations - the framework and the helper file.

https://i.imgur.com/4jwNf9I.png

**Comment by AndresReyesDev** [comment] 2020-03-18 00:52
Duplicate of #126 #451 #469 #516

**Comment by andytan0727** [comment] 2020-03-24 16:49
Facing this problem also. So the fastest solution now is just [disable inspection](https://github.com/barryvdh/laravel-ide-helper/issues/592#issuecomment-355268633) if you are using PhpStorm.

**Comment by shirshak55** [comment] 2020-04-03 07:12
@andytan0727 disable inspection is getting rid of feature not problem.

**Comment by chrisan** [comment] 2020-04-19 18:20
I use the suggestion here so I don't have to disable it: https://github.com/barryvdh/laravel-ide-helper/issues/592#issuecomment-494107327

**Comment by mfn** [comment] 2020-06-27 14:06
@barryvdh the other issue has more details and this doesn't bring much new to the table, IMHO this can be closed as duplicated of #592

**Closed** 2020-06-27 14:42 UTC
