### ISSUE TITLE
PHP 8: Method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by henzeb** [barryvdh/laravel-ide-helper#1110] opened 2020-12-04 09:09 UTC
### Versions:
- ide-helper Version: 2.8.1
- Laravel Version: 8.17.2
- PHP Version: 8.0.0

### Description:

Exception: Method ReflectionParameter::getClass() is deprecated
Could not analyze class App\Models\Users\Employee.

Trace:
0 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(887): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Method Reflecti...', '/var/www/...', 887)
1 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(512): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getParameters(Object(ReflectionMethod))
2 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(250): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getPropertiesFromMethods(Object(App\Models\Users\Employee))
3 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(132): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs(Array, Array)
4 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()

### Steps To Reproduce:

- ./artisan ide-helper:models
- choose no

**Comment by mfn** [comment] 2020-12-04 11:36
Dupe of https://github.com/barryvdh/laravel-ide-helper/issues/1108 and fixed with https://github.com/barryvdh/laravel-ide-helper/pull/1106

Until there's a new release, you can try to use `2.8-dev`!

**Closed by mfn** 2020-12-04 11:36 UTC
Labels: bug
