### ISSUE TITLE
Bug: `ide-helper:models --write` breaks @SuppressWarnings(PHPMD.*) notation

### ISSUE THREAD

**Issue by pablorsk** [barryvdh/laravel-ide-helper#666] opened 2018-05-24 18:19 UTC
When `php artisan ide-helper:models --write` is runned, notations like `@SuppressWarnings(PHPMD.ExcessiveClassComplexity)` was changed to `@SuppressWarnings (PHPMD.ExcessiveClassComplexity)` (check space before `(`).

### Original model
```php
/**
 * @SuppressWarnings(PHPMD.ExcessiveClassComplexity)
 */
class SomeModel extends Model
{
    public function childrens()
    {
        return $this->hasMany(Document::class);
    }
}
```
### After ide-helper:models
```php
/**
 * App\Models\SomeModel
 *
 * @SuppressWarnings (PHPMD.ExcessiveClassComplexity)
 * @property-read \App\Collection|\App\Models\Document[] $childrens
 * @mixin \Eloquent
 */
class SomeModel extends Model
{
    public function childrens()
    {
        return $this->hasMany(Document::class);
    }
}
```

### Diff
```diff
- * @SuppressWarnings(PHPMD.ExcessiveClassComplexity)
+ * @SuppressWarnings (PHPMD.ExcessiveClassComplexity)
```

**Comment by mfn** [comment] 2020-06-26 22:25
I can still reproduce this :-/ I _suspect_ the problem is within https://github.com/barryvdh/ReflectionDocBlock though I could be wrong

**Comment by barryvdh** [comment] 2020-06-27 10:43
I think we might nee a custom tag for that.

**Comment by EspadaV8** [comment] 2021-09-15 03:03
Is there a workaround for this while a fix is implemented?

**Comment by pablorsk** [comment] 2021-09-27 13:48
We have some problems like this, not just PHPMD. Then you can add and customize a script on your `composer.json`:

```
   "scripts": {
        "ide-helper-models":[
            "php artisan migrate",
            "php artisan ide-helper:models --write",
            "find app/* -type f -print0 | xargs -0 sed -i 's/@SuppressWarnings (/@SuppressWarnings(/g'",
            "find app/* -type f -print0 | xargs -0 sed -i 's/@property \\\\Illuminate\\\\Support\\\\Carbon/@property \\\\Carbon\\\\Carbon/g'",
            "find app/* -type f -print0 | xargs -0 sed -i '/* @property int.null $.*_count/d'",
            "find app/* -type f -print0 | xargs -0 sed -i '/* @property-read int.null $.*_count/d'",
            "find app/* -type f -print0 | xargs -0 sed -i -r '/^ \\\\* @method static.*Builder\\\\|\\w+ where\\w+\\(\\$value\\)$/d'"
        ],
    ...
```

Feel free to add or remove lines. For example we remove all where* magic methods, _count properties and change `Illuminate\Support\Carbon` to `Carbon\Carbon`

**Comment by EspadaV8** [comment] 2021-09-27 14:04
Those changes in the composer file feel like a hack rather than a real fix.

Why do the SuppressWarning lines get changed in the first place?

**Comment by EspadaV8** [comment] 2022-11-03 10:54
I have opened an MR that should fix this issue. It is a very small change, so hopefully it can get merged and a new point release will get made :crossed_fingers:

**Comment by EspadaV8** [comment] 2022-11-25 13:17
MR has been merged, so after a version bump has been tagged, it should work without needing any workarounds. Can't believe a 4+ year old bug could be fixed with, basically, a single line change 😅

**Comment by EspadaV8** [comment] 2024-02-08 00:34
Oh, I think this issue can be closed now. The MR for https://github.com/barryvdh/ReflectionDocBlock was merged ages ago, and now https://github.com/barryvdh/laravel-ide-helper has had a new release too.

**Closed** 2024-02-08 05:29 UTC
Labels: bug
