### ISSUE TITLE
Helper does not work with stil/phoebe required in project

### ISSUE THREAD

**Issue by tpavlek** [barryvdh/laravel-ide-helper#157] opened 2015-01-28 20:19 UTC
If my composer.json contains: 

``` json
"stil/phoebe": "dev-master#7bef21bca472c01556780d1fc7e32ccc7781480d as 1.0" 
```

in the require array, then running php artisan ide-helper:generate prints the source code for the ide-helper to the terminal screen.

I've tried to debug, but I have absolutely no idea what would cause something like this to happen.

**Comment by mfn** [comment] 2020-06-25 10:20
The referenced package is pretty old and absolutely failed to get this working in a "modern" codebase: either conflicts of minimum-stability or conflict with roave/security-advisories or not working with monolog 2.0 and the list probably goes on.

The gist is that the generate output was written to stdout.

@barryvdh I vote for closing this as dupe of https://github.com/barryvdh/laravel-ide-helper/issues/695

**Closed** 2020-06-25 11:49 UTC
