### ISSUE TITLE
Error with telegram-bot-sdk

### ISSUE THREAD

**Issue by maicol07** [barryvdh/laravel-ide-helper#1015] opened 2020-08-24 07:27 UTC
Hi,

I'm using the [razasyed/telegram-bot-sdk](https://github.com/irazasyed/telegram-bot-sdk) package but when I generate the ide helper file the IDE cannot recognize the methods because it recognizes the methods of [dingo/api](https://github.com/dingo/api) (the one from telegram is called Api).

Here is the code generated by the ide helper generator:

```php
/**
         * Get a bot instance.
         *
         * @param string $name
         * @throws TelegramSDKException
         * @return \Api 
         * @static 
         */ 
        public static function bot($name = null)
        {
                        /** @var \Telegram\Bot\BotsManager $instance */
                        return $instance->bot($name);
        }
```

The Api class, however, refers to:

```php
class API extends \Dingo\Api\Facade\API {}
```

**Comment by mfn** [comment] 2020-08-24 20:12
I think it's the same problem as https://github.com/barryvdh/laravel-ide-helper/issues/108 ?

**Comment by maicol07** [comment] 2020-08-24 20:14
Yes

**Comment by mfn** [comment] 2020-08-24 20:31
Closing as dupe of https://github.com/barryvdh/laravel-ide-helper/issues/108

**Closed by mfn** 2020-08-24 20:31 UTC
