### ISSUE TITLE
How handle Auth::user() in model

### ISSUE THREAD

**Issue by mgralikowski** [barryvdh/laravel-ide-helper#724] opened 2018-11-14 14:33 UTC
```php
    /**
     * @param  \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeByActiveInstitution($query)
    {
        return $query->where('institution_id', \Auth::user()->institution->id);
    }
```

How can i handle this? Because i get error:

> Exception: Trying to get property 'institution' of non-object
> Could not analyze class App\Models\Form.

Of course i tried some solutions with magic configuration like:

```php
        'Auth' => array(
            'user'     => 'App\Models\User()',
        ),
```

```php
        'Auth' => array(
            'user'     => 'Illuminate\Contracts\Auth\Guard::user',
        ),
```

but without success. This settings are ignored.

My auth config:

```php
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
        'admin' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
    ],
```
I need separate session for admin (i use https://github.com/Laravel-Backpack) but it isn't make any difference.

**Comment by andr3s2** [comment] 2018-12-28 17:19
Try to use the "@" at the begining -  @\Auth::user()->institution->id

**Comment by mfn** [comment] 2020-06-27 04:35
> Exception: Trying to get property 'institution' of non-object

But this indicates that your code is not working, i.e. there's no authenticated user in your current context.

How is this related to the ide-helper package?

Do you still have the problem?

**Comment by quantumwebco** [comment] 2020-09-09 11:39
I have just had this problem. 

I have a relationship that relies on a user id ```return $this->hasOne('App\Models\Answer')->where('user_id', \Auth::user()->id);```

Because it's running on command line there is no logged in user, so when running ```php artisan ide-helper:models``` it throws the error ```Exception: Trying to get property 'id' of non-object
Could not analyze class App\Models\Question.````

suppressing errors with ```@``` works fine as a solution but may not be desirable in an http context

**Comment by mfn** [comment] 2020-09-09 12:22
Thanks, now I **get** the initial description of the problem. Didn't realize the `\Auth::user` as part of the _definition_ of the relation.

Can you show the full stacktrace, please?

**Comment by quantumwebco** [comment] 2020-09-09 12:33
The initial issue is actually to do with a query scope method but they are essentially the same thing. It's more to do with running from cli as there is no user authenticated. The method the ```\Auth::user()``` call is in is mostly irrelevant really as this happens no matter where you put it. I think it's more the fact that it returns null for the user

Stack trace is
```
Exception: Trying to get property 'id' of non-object
Could not analyze class App\Models\Question.

Trace:
#0 \app\Models\Question.php(55): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', 'D:\\work\\spoken\\...', 55, Array)
#1 \vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(573): App\Models\Question->user_answer()
#2 \vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\Relation.php(90): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->Barryvdh\LaravelIdeHelper\Console\{closure}()
#3 \vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(574): Illuminate\Database\Eloquent\Relations\Relation::noConstraints(Object(Closure))
#4 \vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(246): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getPropertiesFromMethods(Object(App\Models\Question))
#5 \vendor\barryvdh\laravel-ide-helper\src\Console\ModelsCommand.php(129): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs(Array, Array)
#6 [internal function]: Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#7 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): call_user_func_array(Array, Array)
#8 \vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#10 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 \vendor\laravel\framework\src\Illuminate\Container\Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 \vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call(Array)
#13 \vendor\symfony\console\Command\Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 \vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 \vendor\symfony\console\Application.php(911): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 \vendor\symfony\console\Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\LaravelIdeHelper\Console\ModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 \vendor\symfony\console\Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 \vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 \vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 \artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}
```

Thanks

**Comment by mfn** [comment] 2020-09-09 13:01
> I guess it could be put in a try catch block so the exception is caught and handled properly?

Yeah, that was my thought too!

Are you up for PR + tests?

**Comment by quantumwebco** [comment] 2020-09-09 13:43
To be honest it's not something I've done before or would be so comfortable doing. 

I know a try/catch block around the if statement on line 468 of ```src/Console/ModelsCommand.php:468``` is a fix. For example
```
/**
     * @param \Illuminate\Database\Eloquent\Model $model
     */
    protected function getPropertiesFromMethods($model)
    {
        $methods = get_class_methods($model);
        if ($methods) {
            sort($methods);
            foreach ($methods as $method) {
                try {
                    if (...)
                    {
                        ...
                    }
                } catch (\Throwable|\Exception $e) {
                    ...
                }
            }
        }
```

But what to do with the exception and how to write test for it I'm not 100% sure with

**Comment by mfn** [comment] 2020-09-10 15:32
np, I no one beats me I might be able to take a a stab at this

**Comment by mfn** [comment] 2020-09-10 19:54
I'm closing this because this is actually already fixed 😅

- I cannot reproduce the original issue with the scope => scopes with references to global state did not exhibit any error
- the other recently mentioned issue with global state in relations, or any kind of error for the matter, was recently solved via https://github.com/barryvdh/laravel-ide-helper/pull/1017 and releases as part of 2.8.1 🎉
- I made a PR to at least tell the user about it, but otherwise there's not much to do: if the relation "can't be executed", we can't figure out the referenced model => https://github.com/barryvdh/laravel-ide-helper/pull/1052

Since I tested all the scenarios and didn't see any bug, I'm going ahead and closing this.

If I made a mistake, please feel free to comment or, preferable, open a new issue with the details.

Thanks!

**Closed by mfn** 2020-09-10 19:54 UTC
Labels: bug
