### ISSUE TITLE
Just cannot get it to work on NetBeans

### ISSUE THREAD

**Issue by ayyobro** [barryvdh/laravel-ide-helper#151] opened 2015-01-09 17:49 UTC
Installed the generator through composer.

added the "scripts".

downloaded 'doctrine' (as per your package's request).

Cleared the artisan compiler.

used 'php artisan ide-helper:generate'

Then ran optimize artisan command

Then I used your example code for my User model.

I see the _ide_helper.php and the _ide_helper_models.php in my project root. 

I'm still getting NOTHING showing up for autocompletion on ANY facade.

Thoughts?

**Comment by jochantrelle** [comment] 2015-02-09 19:40
Hello!, somewhat the same problem here. I use (love) Netbeans 8.0.2. Not trying to complicate life any further by changing my IDE mid-stream while also implementing the Laravel Framework with client's work. Is there any straight forward help/instructions on how to get Laravel projects to open up in Netbeans????

**Comment by marcelopm** [comment] 2017-01-16 05:10
:+1:

**Comment by Caffe1neAdd1ct** [comment] 2017-05-10 09:46
I've had the same issue using the artisan ide-helper:generate version, however the gist L5 generated version works fine with NetBeans 8.2.

https://gist.github.com/barryvdh/5227822

**Comment by phpyii** [comment] 2019-05-07 09:54
In the _ide_helper.php file, modifies if and include method names because NetBeans cannot resolve these keywords

**Comment by mfn** [comment] 2020-06-25 10:09
Is this still an issue for ppl here with the _latest_ Netbeans version (12.0)?

https://github.com/barryvdh/laravel-ide-helper/issues/151#issuecomment-300432183 mentions some L5 generated version works for them to some degree.

> In the _ide_helper.php file, modifies if and include method names because NetBeans cannot resolve these keywords

I only found two places:
- ![image](https://user-images.githubusercontent.com/87493/85700258-7af29500-b6dc-11ea-9627-e4c406d93aaf.png)
- ![image](https://user-images.githubusercontent.com/87493/85700357-965da000-b6dc-11ea-8351-dd688a28b6fc.png)

If they're a problem, then it's definitely an issue with the IDE as this is allowed per PHP and other IDEs work fine with this.

In spirit this is similar to the problem in https://github.com/barryvdh/laravel-ide-helper/issues/655 , the IDEs lack support for certain features nor need IDE-specific workarounds.

**Comment by Caffe1neAdd1ct** [comment] 2020-06-25 10:24
I got round a lot of these issues by introducing a post processor for the ide helper which is called afterward via artisan inside the composer.json:

https://gist.github.com/Caffe1neAdd1ct/826e75a8448575442c464357efcfd429

```
        "post-install-cmd": [
            "@php artisan clear-compiled",
            "@php artisan optimize",
            "@php artisan composer:development"
        ],
        "post-update-cmd": [
            "@php artisan clear-compiled",
            "@php artisan optimize",
            "@php artisan composer:development"
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate",
            "@php artisan clear-compiled",
            "@php artisan optimize",
            "@php artisan composer:development"
        ]
```

Code is from an older project, but might work on newer versions of laravel / the ide helper file. It resolves a lot of the model / query builder completion issues inside netbeans 12.

To be honest some collaboration between the NetBeans PHP module team and Laravel would be great as it is one of the most used / popular frameworks.

**Comment by mfn** [comment] 2020-06-25 12:28
Thanks for the gist!

- `replaceStatic`
  If I'm reading the regex correctly, Netbeans can't handle return types here
- `addEloquentExtends`
  Are you sure this one works as intended? The `_ide_helper_models.php` generated by the latest version creates code like this:
  ```php
  namespace App\Models{
  /**
   * App\Models\SomeModel
   *
   * @property int $id
   * @mixin \Eloquent
   */
  	class SomeModel extends \Eloquent {}
  }
  ```
  I.e. the regex for `/class ([a-zA-Z]+) \{\}/` will not match anything?
- `addEloquentMethods`
  This adds the methods:
  - with
  - where
  - first
  
  It looks to me this is a sign that `@mixins` are not supported, see https://github.com/barryvdh/laravel-ide-helper/issues/151#issuecomment-300432183

Unless I'm mistaken this all points to Netbeans not supporting things which other software (IDEs, static analyzers) can already for some time.

@barryvdh I don't see how ide-helper itself can improve more here at the moment, also here are many issues mixed, some which may be fixed already.

I vote for closing this :}

If there are truly things which could be done in ide-helper, separate issues with more focus on individual interop problems should be created, which are tested with recent versions of Laravel, ide-helper and Netbeans

**Comment by Caffe1neAdd1ct** [comment] 2020-06-25 17:11
@mfn  this was a very old project so most likely looking at the gist a laravel 4 one... would need adjusting for laravel 5/6/7

I'd agree with @mfn ide-helper does the best it can, Netbeans and the like need some work to start supporting the doc hints like other softwares have done for a while. I'll raise a bug report over on apache netbeans.

**Comment by mfn** [comment] 2020-09-24 19:23
>  I'll raise a bug report over on apache netbeans.

@Caffe1neAdd1ct did you create one? If so, any cross reference you can paste?

(though I think it's likely we will close this issue, not much practical benefit)

**Comment by Caffe1neAdd1ct** [comment] 2020-09-26 21:23
@mfn Not yet i'm afraid, with the rapid releases of PHP versions combined with the move over to the Apache foundation the team there had their hands full. I'll get something raised but interested to see what the differences between NetBeans and PHPStorm's autocomplete via docblocks are so the NetBeans team know exactly what is missing... Anyone have a list?

This issue as you say has no practical benefit to the laravel-ide-helper but it would be nice to feed back to the NetBeans PHP module team what we are missing as a PHP community in that IDE :smiley:

**Comment by mfn** [comment] 2020-12-04 00:40
I'm closing this now, basically for the same reason why we closed https://github.com/barryvdh/laravel-ide-helper/issues/654 and a few other issue:
> This file is IDE agnostic and it's up to the IDE to support this; unless there's some specific bug to point out, this should be taken to the IDE vendor

This issue simply has no actionable for the laravel-ide-helper project itself, everyone using Netbeans is encouraged to raise an issue with it or implement it themselves.

**Closed by mfn** 2020-12-04 00:40 UTC
