### ISSUE TITLE
Command give error with latest laravel

### ISSUE THREAD

**Issue by tusharuit25** [barryvdh/laravel-ide-helper#1081] opened 2020-10-20 16:47 UTC
composer require --dev barryvdh laravel-ide-helper
Deprecation warning: require.test-hook is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$". Make sure you fix this as Composer 2.0 will error.

**Comment by mfn** [comment] 2020-10-20 19:38
> composer require --dev barryvdh laravel-ide-helper

I think you meant `composer require --dev barryvdh/laravel-ide-helper` ?

I don't get a deprecation warning with either composer 1 or 2, must be some other package.

Closing as I can't reproduce this and I think it's unrelated to ide-helper.

Happy to assist further if more information is provided:
- your composer.json
- full composer console output

**Closed by mfn** 2020-10-20 19:38 UTC
