### ISSUE TITLE
Full class namespace not detected on doc block

### ISSUE THREAD

**Issue by dorin-niscu** [barryvdh/laravel-ide-helper#685] opened 2018-07-29 11:40 UTC
I added "**use App\Http\Requests\Request;**" in the class.

```
/**
 * Custom method.
 *
 * @param Request $request
 *
 * @return array|mixed
 */
public function customMethod(Request $request) {
}
```

**In ide helper should be** 

```
/**
 * Custom method.
 *
 * @param \App\Http\Requests\Request $request
 * @return array|mixed
 * @static
 */
public static function customMethod($request)
{
}
```

**instead it is** 

```
/**
 * Custom method.
 *
 * @param \Request $request
 * @return array|mixed
 * @static
 */
public static function customMethod($request)
{
}
```

Because of this I get "**Expected \Request, got \App\Http\Requests\Request**".

**Comment by schursin** [comment] 2019-01-11 13:31
bump

**Comment by mfn** [comment] 2020-06-27 03:58
@barryvdh this is a duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/627 , I vote for closing this issue :}

**Closed** 2020-06-27 08:20 UTC
