### ISSUE TITLE
Missing methods on Cartalyst Sentinel

### ISSUE THREAD

**Issue by iboinas** [barryvdh/laravel-ide-helper#250] opened 2015-08-10 16:16 UTC
Hello Barry!

First of all, thanx for this amazing helper!!

I'm implemeting https://github.com/cartalyst/sentinel , version 2,

And some methods, for example hasAnyAccess are not generated by your IDE helper, care to take a look?

Should something be modified on the package side??

Thanks in advance!!

**Comment by bebnev** [comment] 2015-08-10 17:21
Hi. The problem is that some of the methods of Sentinel package are called through `__call` method and are mapped to another Sentinel interfaces. 
So to make autocomplete, you have to tell ide-helper which additional interfaces or classes it needs to parse additionaly. 
So edit the extra config key in `ide-helper.php` like so:
```php
'extra' => array(
...
'Sentinel' => array(
            'Cartalyst\Sentinel\Users\UserRepositoryInterface',
            'Cartalyst\Sentinel\Roles\RoleRepositoryInterface',
            'Cartalyst\Sentinel\Permissions\PermissionsInterface',
            'Cartalyst\Sentinel\Roles\RoleableInterface',
            'Cartalyst\Sentinel\Users\UserInterface'
        )
),
```
and regenerate ide-helper.

**Comment by iboinas** [comment] 2015-08-11 08:30
Awesome! Thank you very much!!

**Comment by bunin** [comment] 2017-06-01 07:30
Hi @bebnev , how about `findRoleBySlug()` method? It doesn't appear after adding extra config.

https://cartalyst.com/manual/sentinel/2.0#roles

**Comment by Abu3safeer** [comment] 2018-03-14 06:04
Thank you very much. 
This is the all Classes and Interfaces I think that might be useful.
``
'Sentinel' => array(
            // Activations
            'Cartalyst\Sentinel\Activations\ActivationInterface',
            'Cartalyst\Sentinel\Activations\ActivationRepositoryInterface',
            'Cartalyst\Sentinel\Activations\EloquentActivation',
            'Cartalyst\Sentinel\Activations\IlluminateActivationRepository',

            // Checkpoints
            'Cartalyst\Sentinel\Checkpoints\ActivationCheckpoint',
            'Cartalyst\Sentinel\Checkpoints\CheckpointInterface',
            'Cartalyst\Sentinel\Checkpoints\NotActivatedException',
            'Cartalyst\Sentinel\Checkpoints\ThrottleCheckpoint',
            'Cartalyst\Sentinel\Checkpoints\ThrottlingException',

            // Cookies
            'Cartalyst\Sentinel\Cookies\CICookie',
            'Cartalyst\Sentinel\Cookies\CookieInterface',
            'Cartalyst\Sentinel\Cookies\FuelPHPCookie',
            'Cartalyst\Sentinel\Cookies\IlluminateCookie',
            'Cartalyst\Sentinel\Cookies\NativeCookie',
            'Cartalyst\Sentinel\Cookies\NullCookie',

            //Hashing
            'Cartalyst\Sentinel\Hashing\BcryptHasher',
            'Cartalyst\Sentinel\Hashing\CallbackHasher',
            'Cartalyst\Sentinel\Hashing\HasherInterface',
            'Cartalyst\Sentinel\Hashing\NativeHasher',
            'Cartalyst\Sentinel\Hashing\Sha256Hasher',
            'Cartalyst\Sentinel\Hashing\WhirlpoolHasher',

            // Native
            'Cartalyst\Sentinel\Native\Facades\Sentinel',
            'Cartalyst\Sentinel\Native\ConfigRepository',
            'Cartalyst\Sentinel\Native\SentinelBootstrapper',

            // Permissions
            'Cartalyst\Sentinel\Permissions\PermissibleInterface',
            'Cartalyst\Sentinel\Permissions\PermissionsInterface',
            'Cartalyst\Sentinel\Permissions\StandardPermissions',
            'Cartalyst\Sentinel\Permissions\StrictPermissions',

            // Persistences
            'Cartalyst\Sentinel\Persistences\EloquentPersistence',
            'Cartalyst\Sentinel\Persistences\IlluminatePersistenceRepository',
            'Cartalyst\Sentinel\Persistences\PersistableInterface',
            'Cartalyst\Sentinel\Persistences\PersistenceInterface',
            'Cartalyst\Sentinel\Persistences\PersistenceRepositoryInterface',

            // Reminders
            'Cartalyst\Sentinel\Reminders\EloquentReminder',
            'Cartalyst\Sentinel\Reminders\IlluminateReminderRepository',
            'Cartalyst\Sentinel\Reminders\ReminderRepositoryInterface',

            // Roles
            'Cartalyst\Sentinel\Roles\EloquentRole',
            'Cartalyst\Sentinel\Roles\IlluminateRoleRepository',
            'Cartalyst\Sentinel\Roles\RoleableInterface',
            'Cartalyst\Sentinel\Roles\RoleInterface',
            'Cartalyst\Sentinel\Roles\RoleRepositoryInterface',

            // Sessions
            'Cartalyst\Sentinel\Sessions\CISession',
            'Cartalyst\Sentinel\Sessions\FuelPHPSession',
            'Cartalyst\Sentinel\Sessions\IlluminateSession',
            'Cartalyst\Sentinel\Sessions\NativeSession',
            'Cartalyst\Sentinel\Sessions\SessionInterface',

            // Throttling
            'Cartalyst\Sentinel\Throttling\EloquentThrottle',
            'Cartalyst\Sentinel\Throttling\IlluminateThrottleRepository',
            'Cartalyst\Sentinel\Throttling\ThrottleRepositoryInterface',

            // Users
            'Cartalyst\Sentinel\Users\EloquentUser',
            'Cartalyst\Sentinel\Users\IlluminateUserRepository',
            'Cartalyst\Sentinel\Users\UserInterface',
            'Cartalyst\Sentinel\Users\UserRepositoryInterface',

            // Cartalyst\Sentinel
            'Cartalyst\Sentinel\Sentinel',
        ),
``

**Comment by pahan35** [comment] 2018-09-26 14:21
@Abu3safeer @bebnev looks like these lists don't work anymore due to an exception on [line 306](https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Alias.php#L306)
``list($className, $name) = explode('::', $real);``

Has anyone any proposal how to allow use these lists again without manually defining the whole methods?

**Comment by mfn** [comment] 2020-06-25 14:45
The facade can decide to document them in the class phpdoc with the `@method` annotation, otherwise it's impossible to introspec what "magic is going on in __call 🧙 " (besides the manual listing which also works); the annotations are correctly used in `_ide_helper.php` nowadays (it probably didn't 5 years ago)

@barryvdh I think we can close this issue :}

**Closed** 2020-06-26 05:05 UTC
